# Generated by Django 6.0.5 on 2026-05-17 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='cantidad',
            field=models.DecimalField(decimal_places=8, max_digits=15),
        ),
    ]
