# Generated by Django 6.0.5 on 2026-05-17 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_compra_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activo',
            name='cantidad',
            field=models.DecimalField(decimal_places=8, max_digits=15),
        ),
    ]
