# Generated by Django 6.0.5 on 2026-05-17 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_activo_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dividendo',
            name='cambio_nominal',
            field=models.DecimalField(decimal_places=8, max_digits=15),
        ),
    ]
