# Generated by Django 6.0.5 on 2026-06-03 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_dividendo_cambio_nominal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activo',
            name='cantidad',
        ),
    ]
