# Generated by Django 6.0.5 on 2026-06-04 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_historial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activo',
            name='precio',
        ),
    ]
