# Generated by Django 6.0.5 on 2026-06-04 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_remove_activo_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='cambio_divisa',
            field=models.DecimalField(decimal_places=6, default=1, max_digits=10),
        ),
    ]
