# Generated by Django 6.0.5 on 2026-06-04 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_compra_cambio_divisa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='cambio_divisa',
            field=models.DecimalField(decimal_places=8, default=1, max_digits=10),
        ),
    ]
