# Generated by Django 6.0.5 on 2026-08-27 00:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_alter_compra_cambio_divisa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='activo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras', to='portfolio.activo'),
        ),
        migrations.AlterField(
            model_name='dividendo',
            name='activo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dividendos', to='portfolio.activo'),
        ),
        migrations.AlterField(
            model_name='historial',
            name='activo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='portfolio.activo'),
        ),
    ]
